name: ca_environment
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.0.2
  - python=3.6.10
  - readline=8.0
  - setuptools=46.1.3
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - blis==0.4.1
    - catalogue==1.0.0
    - chardet==3.0.4
    - cycler==0.10.0
    - cymem==2.0.3
    - idna==2.9
    - importlib-metadata==1.6.0
    - joblib==0.14.1
    - kiwisolver==1.2.0
    - matplotlib==3.2.1
    - murmurhash==1.0.2
    - numpy==1.18.3
    - pandas==1.0.3
    - plac==1.1.3
    - preshed==3.0.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - requests==2.23.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - six==1.14.0
    - spacy==2.2.4
    - srsly==1.0.2
    - thinc==7.4.0
    - tqdm==4.45.0
    - urllib3==1.25.9
    - wasabi==0.6.0
    - zipp==3.1.0
